# Generated by Django 5.2.1 on 2025-05-23 23:43

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_number', models.CharField(default='', max_length=100, unique=True, verbose_name="Numéro d'opportunité")),
                ('client_name', models.CharField(default='', max_length=255, verbose_name='Nom du client')),
                ('guarantee_type', models.CharField(choices=[('DO', 'DO seule'), ('TRC', 'TRC seule'), ('DUO', 'DUO (DO + TRC)')], default='DO', max_length=10, verbose_name='Quel type de garantie')),
                ('ouvrage_destination', models.CharField(blank=True, choices=[('HABITATION', 'Habitation'), ('HORS_HABITATION', 'Hors Habitation')], default='HABITATION', max_length=20, verbose_name="Quel est la destination de l'ouvrage ?")),
                ('work_type', models.CharField(choices=[('NEUF', 'Ouvrage Neuf'), ('RENOVATIONLE', 'Rénovation légère'), ('RENOVATIONLD', 'Rénovation lourde')], default='NEUF', max_length=20, verbose_name='Quels types de travaux sont réalisés ?')),
                ('ouvrage_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name="Coût de l'ouvrage")),
                ('existing_presence', models.BooleanField(default=False, verbose_name="Présence d'existant")),
                ('is_vip_client', models.BooleanField(default=False, verbose_name='Votre Client est-il un VIP')),
                ('rcmo_desired', models.BooleanField(default=False, verbose_name='Souhaitez vous la RCMO')),
                ('trc_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Taux Seul Tarif TRC')),
                ('do_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Taux Seul Tarif DO')),
                ('prime_seule_tarif_trc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prime Seule Tarif TRC')),
                ('prime_seule_tarif_do', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prime Seule Tarif DO')),
                ('prime_seule_tarif_duo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prime Seule Tarif DUO')),
                ('ouvrage_description', models.TextField(blank=True, null=True, verbose_name="Description de l'ouvrage")),
                ('address_chantier', models.TextField(blank=True, null=True, verbose_name='Adresse du chantier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Proposition de devis',
                'verbose_name_plural': 'Propositions de devis',
            },
        ),
        migrations.CreateModel(
            name='ProposalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name="IP de l'utilisateur")),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de modification')),
                ('changes', models.JSONField(verbose_name='Changements')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='django_api.proposal', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Historique de modification de devis',
                'verbose_name_plural': 'Historiques des modifications de devis',
                'ordering': ['-timestamp'],
            },
        ),
    ]
